# Generated by Django 3.2.11 on 2022-01-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Idea', models.CharField(max_length=250)),
                ('Date', models.DateTimeField()),
                ('Describe_Your_Idea', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='progresse',
            name='Notes',
            field=models.TextField(blank=True, max_length=7500),
        ),
    ]
