# Generated by Django 3.2.11 on 2022-01-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20220115_0332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteIdeas',
            new_name='WebsiteIdea',
        ),
    ]
