# Generated by Django 3.2.11 on 2022-01-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_progresse_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualStudioCodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Date', models.DateTimeField()),
                ('Link', models.TextField(max_length=1000)),
            ],
        ),
    ]
