# Generated by Django 3.2.11 on 2022-01-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_visualstudiocodelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualstudiocodelink',
            name='Link',
            field=models.URLField(max_length=1000),
        ),
    ]
