# Generated by Django 3.2.11 on 2022-01-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Assignment', models.CharField(max_length=50)),
                ('Date_Assigned', models.DateTimeField()),
                ('Assigned_To', models.CharField(choices=[('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5)),
                ('Assigned_By', models.CharField(choices=[('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5)),
                ('Task', models.CharField(max_length=250)),
                ('Due_Date', models.DateField()),
                ('Description', models.TextField(max_length=1000)),
                ('Link', models.URLField(max_length=2000)),
                ('Optional_Link', models.URLField(blank=True, max_length=2000)),
            ],
        ),
    ]
