# Generated by Django 3.2.11 on 2022-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assigned_By',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Assigned_To',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
    ]
