# Generated by Django 3.2.11 on 2022-01-27 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_auto_20220127_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Resolved',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Yes', 'Yes'), ('Postponed', 'Postponed'), ('Action Canceled', 'Action Canceled')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
