# Generated by Django 3.2.11 on 2022-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_assignment_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Most_Important_Message',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
