# Generated by Django 3.2.11 on 2022-01-27 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_assignment_most_important_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Most_Important_Message',
            new_name='Latest_Important_Message',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Latest_Message_Posted_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
