# Generated by Django 3.2.11 on 2022-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_auto_20220127_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Latest_Message_Posted_At',
            field=models.TimeField(),
        ),
    ]
