# Generated by Django 3.2.11 on 2022-01-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_alter_assignment_latest_message_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Latest_Message_Posted_At',
            new_name='Message_Posted_At',
        ),
    ]
