# Generated by Django 3.2.11 on 2022-01-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_rename_latest_message_posted_at_assignment_message_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Latest_Important_Message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Message_Posted_At',
            field=models.TimeField(blank=True),
        ),
    ]
