# Generated by Django 3.2.11 on 2022-01-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0016_auto_20220127_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Message_Posted_At',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
