# Generated by Django 3.2.11 on 2022-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_alter_assignment_message_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Less_Important_Messages_And_Chat',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
