# Generated by Django 3.2.11 on 2022-01-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0020_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Response',
            field=models.CharField(default='Type your response here.', max_length=250),
        ),
        migrations.AlterField(
            model_name='messages',
            name='From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=255),
        ),
    ]
