# Generated by Django 3.2.11 on 2022-02-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0023_auto_20220201_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Time_Of_Response',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
