# Generated by Django 3.2.11 on 2022-02-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0024_alter_messages_time_of_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Response_From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], default='test', max_length=10),
        ),
    ]
