# Generated by Django 3.2.11 on 2022-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0025_messages_response_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='munchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('Munchy_message', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Resolved',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Yes', 'Yes'), ('Postponed', 'Postponed'), ('bye bye bye', 'gone'), ('Out The Window!(Canceled)', 'Out The Window!(Canceled)')], max_length=30),
        ),
    ]
