# Generated by Django 3.2.11 on 2022-02-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0027_rename_data_munchy_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='munchy',
        ),
    ]
