# Generated by Django 3.2.11 on 2022-02-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0028_delete_munchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Resolved',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Yes', 'Yes'), ('Postponed', 'Postponed'), ('Canceled', 'Canceled'), ('Out The Window!(No More)', 'Out The Window!(No More)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Response_From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=10),
        ),
    ]
