# Generated by Django 3.2.11 on 2022-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0028_delete_munchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Upload_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('File_Name', models.CharField(max_length=250)),
                ('Upload_File', models.FileField(upload_to='')),
                ('Description', models.TextField(max_length=250)),
            ],
        ),
    ]
