# Generated by Django 3.2.11 on 2022-02-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0029_file_upload_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Link',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Name_Of_Assignment',
            field=models.CharField(max_length=150),
        ),
    ]
