# Generated by Django 4.0.2 on 2022-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0030_auto_20220204_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Optional_Link',
            new_name='Optional_Link1',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Optional_Link2',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Optional_Link3',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Resolved',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Yes', 'Yes'), ('Postponed', 'Postponed'), ('Out The Window!(Canceled)', 'Out The Window!(Canceled)')], max_length=30),
        ),
    ]
