# Generated by Django 4.0.2 on 2022-02-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0031_rename_optional_link_assignment_optional_link1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Optional_Link1',
            new_name='Optional_Link',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='Optional_Link2',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='Optional_Link3',
        ),
    ]
