# Generated by Django 4.0.2 on 2022-02-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0032_rename_optional_link1_assignment_optional_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Optional_Link',
            new_name='Optional_Link_2',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Optional_Link_1',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Optional_Link_3',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
