# Generated by Django 3.2.11 on 2022-02-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0034_rename_assigned_to_assignment_primary_assigned_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
