# Generated by Django 4.0.2 on 2022-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0035_delete_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Task',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
