# Generated by Django 4.0.2 on 2022-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0036_alter_assignment_description_alter_assignment_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(blank=True, max_length=500)),
                ('Due', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_Name', models.CharField(max_length=500)),
                ('Document_Link', models.URLField(max_length=2500)),
            ],
        ),
    ]
