# Generated by Django 3.2.12 on 2022-02-16 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0036_alter_assignment_description_alter_assignment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Response',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Response_From',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Time_Of_Response',
        ),
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='-----', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Message',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='messages',
            name='To',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
    ]
