# Generated by Django 3.2.12 on 2022-02-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0037_auto_20220216_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='name',
        ),
    ]
