# Generated by Django 3.2.12 on 2022-02-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0038_remove_messages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='Message',
            field=models.TextField(max_length=700),
        ),
    ]
