# Generated by Django 3.2.12 on 2022-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0039_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='From',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
        migrations.AlterField(
            model_name='messages',
            name='To',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
