# Generated by Django 3.2.12 on 2022-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0040_auto_20220217_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
