# Generated by Django 3.2.12 on 2022-02-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0043_auto_20220217_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='availability',
            name='On_Docs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
    ]
