# Generated by Django 3.2.12 on 2022-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0044_auto_20220217_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='Notes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
