# Generated by Django 3.2.12 on 2022-02-17 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0045_availability_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='Updated_At',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
