# Generated by Django 3.2.11 on 2022-02-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0037_scheduledtasks_statuses'),
        ('progress', '0048_alter_availability_updated_at'),
    ]

    operations = [
    ]
