# Generated by Django 3.2.11 on 2022-02-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0049_merge_20220217_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledTasks',
            new_name='ScheduledTask',
        ),
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Statuse',
        ),
    ]
