# Generated by Django 4.0.2 on 2022-02-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0050_auto_20220217_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='Resolved',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Yes', 'Yes'), ('Postponed', 'Postponed'), ('Out The Window!(Canceled)', 'Out The Window!(Canceled)')], default='-----', max_length=30),
            preserve_default=False,
        ),
    ]
