# Generated by Django 4.0.2 on 2022-02-18 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0051_scheduledtask_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='Due',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='Due_At',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
