# Generated by Django 4.0.2 on 2022-02-18 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0052_remove_scheduledtask_due_scheduledtask_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuse',
            name='Date_Published',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
