# Generated by Django 4.0.2 on 2022-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0054_message_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.TextField(max_length=135),
        ),
    ]
