# Generated by Django 4.0.2 on 2022-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0055_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='Updated_At',
        ),
        migrations.AddField(
            model_name='availability',
            name='Updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
