# Generated by Django 4.0.4 on 2022-05-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0058_auto_20220405_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='To',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5),
        ),
    ]
