# Generated by Django 4.1 on 2022-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0059_alter_message_from_alter_message_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=50)),
                ('lastName', models.CharField(db_column='last_name', max_length=50)),
                ('email', models.CharField(db_column='user_email', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
