# Generated by Django 3.1.4 on 2022-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchyblog', '0002_auto_20220318_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='Header1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Header2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Header2_Second_Paragraph',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Header3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Header3_Second_Paragraph',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='IntroParagraph',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Paragraph1',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Paragraph2',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Paragraph3',
            field=models.TextField(blank=True, max_length='1000'),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Post_Title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='SecondParagraph',
            field=models.TextField(blank=True, max_length='1000'),
        ),
    ]
