# Generated by Django 3.2.11 on 2022-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchyblog', '0003_auto_20220318_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeblog',
            name='Embeded',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Post_Author_MunchySite_Admin_Purposes_Only',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L'), ('C,G', 'C,G')], max_length=5),
        ),
    ]
