# Generated by Django 3.2.11 on 2022-04-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munchyblog', '0004_auto_20220405_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblog',
            name='Embeded',
        ),
    ]
