# Generated by Django 3.2.11 on 2022-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchyblog', '0006_merge_20220412_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblog',
            name='Author',
            field=models.CharField(choices=[('MunchyTeam Moderator', 'MunchyTeam Moderator'), ('AS', 'AS'), ('Calvin', 'Calvin'), ('LS', 'LS'), ('Hudson Crisp', 'Hudson Crisp'), ('Carson', 'Carson'), ('MunchyBlog Author', 'MunchyBlog Author')], max_length=30),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Post_Author_MunchySite_Admin_Purposes_Only',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L'), ('C,G', 'C,G'), ('Other', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='Post_Title',
            field=models.CharField(max_length=200),
        ),
    ]
