# Generated by Django 4.0.6 on 2022-07-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1_Heading', models.CharField(blank=True, help_text='There can only be one heading. This is the main heading on banner on the homepage', max_length=23)),
                ('MCI', models.CharField(blank=True, help_text='This should be a number for MCI.', max_length=10)),
                ('AMG', models.CharField(blank=True, help_text='This should be a number for AMG.', max_length=10)),
                ('Button1', models.CharField(blank=True, help_text='This will the name for the first button on the economy banner on the homepage.', max_length=300)),
                ('Hyperlink_of_Button1', models.CharField(blank=True, help_text='This is the hyperlink for button 1. Please include "https://" and the full link for the button.', max_length=7000)),
                ('Small_Text_1', models.CharField(blank=True, help_text='The small text in the economy banner', max_length=500)),
                ('Small_Text_2', models.CharField(blank=True, help_text='The small text in the economy banner', max_length=500)),
                ('Small_Text_3', models.CharField(blank=True, help_text='The small text in the economy banner', max_length=500)),
            ],
        ),
    ]
