# Generated by Django 4.0.6 on 2022-07-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1homepage', '0002_economy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_class', models.CharField(blank=True, help_text='List the classes for the div for the main banner background. THIS WILL ONLY WORK FOR THE MAIN BANNER.', max_length=250)),
                ('style', models.TextField(blank=True, help_text='List the style for the div for the main banner background.THIS WILL ONLY WORK FOR THE MAIN BANNER.', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='adminbanner',
            name='div_class',
            field=models.CharField(blank=True, help_text='List the classes for the div for the main banner background. THIS WILL ONLY WORK FOR THE INFO BANNER.', max_length=250),
        ),
        migrations.AddField(
            model_name='adminbanner',
            name='style',
            field=models.TextField(blank=True, help_text='List the style for the div for the main banner background. THIS WILL ONLY WORK FOR THE INFO BANNER.', max_length=1000),
        ),
        migrations.AddField(
            model_name='economy',
            name='div_class',
            field=models.CharField(blank=True, help_text='List the classes for the div for the main banner background. THIS WILL ONLY WORK FOR THE MUNCHYWAR ECONOMY BANNER.', max_length=250),
        ),
        migrations.AddField(
            model_name='economy',
            name='style',
            field=models.TextField(blank=True, help_text='List the style for the div for the main banner background.THIS WILL ONLY WORK FOR THE MUNCHYWAR ECONOMY BANNER. ', max_length=1000),
        ),
    ]
