# Generated by Django 4.0.6 on 2022-07-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1homepage', '0003_bannerbackground_adminbanner_div_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbanner',
            name='Notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='banner',
            name='Notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='bannerbackground',
            name='Notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='economy',
            name='Notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
