# Generated by Django 4.0.6 on 2022-07-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1homepage', '0004_adminbanner_notes_banner_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerbackground',
            name='div_class_info_banner',
            field=models.CharField(blank=True, help_text='List the classes for the div for the main banner background. THIS WILL ONLY WORK FOR THE MAIN BANNER.', max_length=250),
        ),
        migrations.AddField(
            model_name='bannerbackground',
            name='style_info_banner',
            field=models.TextField(blank=True, help_text='List the style for the div for the main banner background.THIS WILL ONLY WORK FOR THE MAIN BANNER.', max_length=1000),
        ),
    ]
