# Generated by Django 4.0.2 on 2022-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('drive_file_link', models.URLField(max_length=1000)),
                ('Name_of_file', models.CharField(max_length=100)),
            ],
        ),
    ]
