# Generated by Django 4.0.2 on 2022-02-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_driveuploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='munchy',
            old_name='Munchy_message',
            new_name='Munchy_Message',
        ),
        migrations.AddField(
            model_name='munchy',
            name='From',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], default='-----', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='munchy',
            name='To',
            field=models.CharField(choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], default='-----', max_length=5),
            preserve_default=False,
        ),
    ]
