# Generated by Django 4.0.2 on 2022-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_rename_munchy_message_munchy_munchy_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveuploader',
            name='Dropbox_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
