# Generated by Django 4.0.2 on 2022-02-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_driveuploader_dropbox_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveuploader',
            name='Dropbox_link',
        ),
    ]
