# Generated by Django 3.2.11 on 2022-02-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_alter_driveuploader_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveuploader',
            name='File_Link',
            field=models.URLField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='driveuploader',
            name='File_Type',
            field=models.CharField(choices=[('-----', '-----'), ('Drive', 'Drive'), ('.docx', '.docx'), ('.xlsx', '.xlsx'), ('.pptx', '.pptx'), ('.pdf', '.pdf'), ('Other', 'Other')], default='-----', max_length=10),
        ),
        migrations.AlterField(
            model_name='driveuploader',
            name='drive_file_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
