# Generated by Django 3.2.11 on 2022-02-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20220217_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveuploader',
            name='File_Type',
            field=models.CharField(choices=[('-----', '-----'), ('Drive', 'Drive'), ('munchy', 'munchy'), ('.docx', '.docx'), ('.xlsx', '.xlsx'), ('.pptx', '.pptx'), ('.pdf', '.pdf'), ('Other', 'Other')], default='-----', max_length=10),
        ),
    ]
