# Generated by Django 4.0.2 on 2022-02-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_driveuploader_dropbox_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveuploader',
            name='Dropbox_Link',
            field=models.CharField(blank=True, choices=[('dropbox.com', 'dropbox.com')], help_text='If file is on Dropbox, select dropbox.com, otherwise leave blank.', max_length=25),
        ),
        migrations.AlterField(
            model_name='driveuploader',
            name='File_Location',
            field=models.CharField(blank=True, choices=[('OneDrive', 'OneDrive'), ('Dropbox', 'Dropbox'), ('Google Drive', 'Google Drive')], max_length=20),
        ),
    ]
