# Generated by Django 4.0.6 on 2022-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='H1_Heading',
            field=models.CharField(blank=True, help_text='There can only be one heading. This is the main heading on banner on the homepage', max_length=36),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Paragraph',
            field=models.CharField(blank=True, help_text='There can only be one paragraph. This is the main paragraph on banner on the homepage', max_length=250),
        ),
    ]
