# Generated by Django 4.0.6 on 2022-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_banner_h1_heading_alter_banner_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Hyperlink_of_Button4',
            field=models.CharField(blank=True, help_text='This is the hyperlink for button 4. Please include "https://" and the full link for the button.', max_length=7000),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Hyperlink_of_Button1',
            field=models.CharField(blank=True, help_text='This is the hyperlink for button 1. Please include "https://" and the full link for the button.', max_length=7000),
        ),
    ]
