# Generated by Django 4.0.6 on 2022-07-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_banner_hyperlink_of_button4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1_Heading', models.CharField(blank=True, help_text='There can only be one heading. This is the main heading on banner on the homepage', max_length=36)),
                ('Paragraph', models.CharField(blank=True, help_text='There can only be one paragraph. This is the main paragraph on banner on the homepage', max_length=250)),
                ('Link_or_Button_Name_For_Button_1', models.CharField(blank=True, help_text='This will the name for the first button on the banner on the homepage.', max_length=20)),
                ('Hyperlink_of_Button1', models.CharField(blank=True, help_text='This is the hyperlink for button 1. Please include "https://" and the full link for the button.', max_length=7000)),
                ('Link_or_Button_Name_For_Button_2', models.CharField(blank=True, help_text='This will the name for the second button on the banner on the homepage.', max_length=20)),
                ('Hyperlink_of_Button2', models.CharField(blank=True, help_text='This is the hyperlink for button 2. Please include "https://" and the full link for the button.', max_length=7000)),
                ('Link_or_Button_Name_For_Button_3', models.CharField(blank=True, help_text='This will the name for the third button on the banner on the homepage.', max_length=20)),
                ('Hyperlink_of_Button3', models.CharField(blank=True, help_text='This is the hyperlink for button 3. Please include "https://" and the full link for the button.', max_length=7000)),
                ('Link_or_Button_Name_For_Button_4', models.CharField(blank=True, help_text='This will the name for the fourth button on the banner on the homepage.', max_length=20)),
                ('Hyperlink_of_Button4', models.CharField(blank=True, help_text='This is the hyperlink for button 4. Please include "https://" and the full link for the button.', max_length=7000)),
            ],
        ),
    ]
