# Generated by Django 4.0.6 on 2022-07-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_admin_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Banner',
            new_name='AdminBanner',
        ),
    ]
