# Generated by Django 3.2.11 on 2022-02-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='Link_Name',
            field=models.CharField(default='-----', max_length=250),
        ),
        migrations.AddField(
            model_name='link',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='URL',
            field=models.URLField(blank=True, max_length=7501),
        ),
    ]
