# Generated by Django 3.2.11 on 2022-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0002_auto_20220202_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='URL',
            field=models.URLField(max_length=7501, null=True),
        ),
    ]
