# Generated by Django 3.2.11 on 2022-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0003_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='Link_Name',
            field=models.CharField(max_length=250),
        ),
    ]
