# Generated by Django 3.2.11 on 2022-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0004_alter_link_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='Munchy_ID',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
