# Generated by Django 3.1.4 on 2022-03-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MunchyApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField()),
                ('AppName', models.CharField(blank=True, max_length=500)),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('DownloadLink', models.URLField(blank=True, help_text='This is going to be the link of the publish.htm file on GitHub, or basically the screen where users can click download and the app will be downloaded', max_length=5000)),
                ('AppCreator', models.CharField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], max_length=5)),
            ],
        ),
    ]
