# Generated by Django 3.1.4 on 2022-03-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MunchyApps',
            new_name='MunchyApp',
        ),
    ]
