# Generated by Django 3.1.4 on 2022-03-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220320_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='munchyapp',
            name='InstructionsLink',
            field=models.URLField(blank=True, choices=[('test', 'test'), ('C,H', 'C,H'), ('S,A', 'S,A'), ('S,L', 'S,L')], help_text='Include a Dropbox document link, Google Doc link, or a Microsoft Word via OneDrive link to help users to learn on how to install and use our apps.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='munchyapp',
            name='DateCreated',
            field=models.DateField(blank=True),
        ),
    ]
