# Generated by Django 3.2.11 on 2022-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20220320_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munchyapp',
            name='InstructionsLink',
            field=models.URLField(blank=True, help_text='Include a Dropbox document link, Google Doc link, or a Microsoft Word via OneDrive link to help users to learn on how to install and use our apps.', max_length=5000),
        ),
    ]
