# Generated by Django 3.2.11 on 2022-04-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_munchyapp_instructionslink'),
        ('apps', '0004_auto_20220407_1821'),
    ]

    operations = [
    ]
