# Generated by Django 3.2.11 on 2022-02-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File',
            field=models.FileField(upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
