# Generated by Django 3.2.11 on 2022-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploads', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File',
            field=models.FileField(upload_to='files/'),
        ),
    ]
